# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$all\
$line_break\
$character"""

palette = "catppuccin_mocha"
command_timeout = 1000

[docker_context]
format = '\[[$symbol$context]($style)\]'

[fill]
symbol = " "

[git_branch]
format = '[$symbol$branch]($style) '
ignore_branches = ['develop', 'main']
style = "peach"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[directory]
style = "green"

[gcloud]
disabled = true

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[gradle]
format = '[$symbol($version )]($style)'

[java]
format = '[${symbol}(${version} )]($style)'

[kotlin]
format = '[$symbol($version )]($style)'
symbol = '🅺 '

[nodejs]
format = "[$symbol($version)]($style) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
format = '[$symbol($version )]($style)'
symbol = '🔺 '

[rust]
symbol = " "

[swift]
format = '[$symbol($version )]($style)'

[time]
disabled = true
format = "[$time]($style)"
style = "flamingo"
time_format = '%R'

[zig]
format = '[$symbol($version )]($style)'
symbol = '⚡️ '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
