theme = "tokyonight_storm"

[editor]
auto-save = true
bufferline = "multiple"
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
line-number = "relative"
mouse = false
rulers = [120]
true-color = true

# [keys.insert]
# j = { k = "normal_mode" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true
# display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "error"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-t = [":new", ":insert-output gitui", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
