theme = "tokyonight"

[editor]
auto-save = true
line-number = "relative"
mouse = false
true-color = true
cursorline = true
bufferline = "multiple"
rulers = [120]
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[keys.insert]
j = { k = "normal_mode" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-messages = true
auto-signature-help = false
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-g = [":new", ":insert-output /opt/homebrew/bin/gitui", ":buffer-close!", ":redraw"]
